name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - pipeline*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
          
    - name: Run tests
      run: pytest

  deploy:
   name: Deploy
   runs-on: ubuntu-latest
   steps:
     - name: Checkout Repository
       uses: actions/checkout@v4
     - name: Set up Google Cloud SDK
       uses: google-github-actions/setup-gcloud@v0.2.0
       with:
         service_account_key: ${{ secrets.GCP_SA_KEY }}
         project_id: ${{ secrets.GCP_PROJECT_ID }}
         export_default_credentials: true
     - name: Install Python
       uses: actions/setup-python@v4
       with:
         python-version: 3.11
     - name: Install Dependencies
       run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
     - name: Deploy Flask App
       run: |
         # Use gcloud command to deploy Flask app to existing Google Compute Engine instance
         gcloud app deploy app.yaml --project=cs490-skyline-automotive --version=1
     - name: Connect to Cloud SQL
       run: |
         # Use gcloud command to connect to existing Cloud SQL instance
         gcloud sql connect backend-skyline --user=root --quiet